export const ISAUTHORIZATION = "USER/ISAUTHORIZATION";
export const TOKEN = "USER/TOKEN";

export const FETCHING_BOOKS = "LIBRARY/FETCHING_BOOKS";
export const FETCHED_BOOKS = "LIBRARY/FETCHED_BOOKS";
export const FETCHED_BOOKS_ERROR = "LIBRARY/FETCHED_BOOKS_ERROR";

export const FETCHING_FAVORITE = "LIBRARY/FETCHING_FAVORITE";
export const FETCHED_LIBRARY_FAVORITE = "LIBRARY/FETCHED_LIBRARY_FAVORITE";
export const FETCHED_DASHBOARD_FAVORITE = "LIBRARY/FETCHED_DASHBOARD_FAVORITE";
export const FETCHED_FAVORITE_ERROR = "LIBRARY/FETCHED_FAVORITE_ERROR";

export const FETCHING_USER_DATA = "LIBRARY/FETCHING_USER_DATA";
export const FETCHED_USER_DATA = "LIBRARY/FETCHED_USER_DATA";
export const FETCHED_USER_DATA_ERROR = "LIBRARY/FETCHED_USER_DATA_ERROR";

export const ERROR_MESSAGE = "APP/ERROR_MESSAGE";
export const CHANGE_LOADING = "APP/CHANGE_LOADING";
export const WATCHER_GET_BOOKS = "APP/WATCHER_GET_BOOKS";
export const WATCHER_GET_USER_DATA = "APP/WATCHER_GET_USER_DATA";
export const WATCHER_CHECK_AUTH = "APP/WATCHER_CHECK_AUTH";
export const WATCHER_DELETE_BOOKS = "APP/ WATCHER_DELETE_BOOKS";

// export const FETCH_USER_DATA = "USER/FETCH_USER_DATA";
// export const USER_LOGIN = "USER/USER_LOGIN";
// export const USER_PASSWORD = "USER/USER_PASSWORD";
// export const SHOW_SPINNER = "APP/SHOW_SPINNER";
// export const HIDE_SPINNER = "APP/HIDE_SPINNER";
// export const SHOW_ALERT = "APP/SHOW_ALERT";
// export const HIDE_ALERT = "APP/HIDE_ALERT";
